[package]
name = "wled-json-api-library"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
log = "0.4.20"
reqwest = { version = "0.11.22", features = ["gzip"] }
serde_repr = "0.1.17"

